services:

  postgres:
    image: postgres:17.4
    restart: "no"
    ports:
      - "${SPRING_DATASOURCE_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      POSTGRES_DB: ${SPRING_DATASOURCE_DB}
      TZ: Asia/Yekaterinburg
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5
    env_file:
      - .env

#  bordex-back:
#    image: busylefthand2009/bordex-back:1.1
#    restart: "no"
#    ports:
#      - "8080:8080"
#    depends_on:
#      postgres:
#        condition: service_healthy
#    environment:
#      TZ: Asia/Yekaterinburg
#    env_file:
#      - .env

volumes:
  postgres_data:
